#!/bin/bash

# Delete some potential conflicting files
HOME_PREFIX=$HOME # Production mode: affect $HOME
AUTH_FILEPATH=$HOME_PREFIX"/.ssh/authorized_keys"
HOME_BIN_PREFIX=$HOME_PREFIX"/bin"

# This is mainly usefull for debugging, to make sure the home folder are create
if [ ! -d $HOME_PREFIX ]; then
	mkdir -p $HOME_PREFIX
fi

if [ ! -d $HOME_PREFIX"/.ssh" ]; then
	mkdir $HOME_PREFIX"/.ssh"
fi

# Adding my public keys
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/authorized_keys -O $AUTH_FILEPATH

# Setting proper permissions on .ssh and authorized_keys
chmod 700 $HOME_PREFIX"/.ssh"
chmod 600 $HOME_PREFIX"/.ssh/authorized_keys"

# Installing the helper scripts
if [ ! -d $HOME_PREFIX"/bin" ]; then
	mkdir $HOME_PREFIX"/bin"
fi

if [ ! -d $HOME_PREFIX"/.config" ]; then
	mkdir $HOME_PREFIX"/.config"
fi

# Download the bashrc
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/dot_bashrc -O $HOME_PREFIX"/.bashrc"

# Donwload the sshconfig file
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/ssh_config -O $HOME_PREFIX"/.ssh/config"

# Bonus: youtubedl config
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/yt-dlp.conf -O $HOME_PREFIX"/.config/yt-dlp.conf"

# Downdload the port and remote hostname in case there was an update upstream
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/m/DEFAULT_PORT -O $HOME_BIN_PREFIX"/DEFAULT_PORT"
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/REMOTE_HOSTNAME -O $HOME_BIN_PREFIX"/REMOTE_HOSTNAME"

# Download the reverse ssh helper script to the ~/bin
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/revshell1 -O $HOME_BIN_PREFIX"/revshell"

# Donw the vnc forwarding script to the ~/bin folder and apply the permissions
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/killrevshell1 -O $HOME_BIN_PREFIX"/killrevshell"

# Bonus: download youtube-dl script via termux
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/termux-url-opener -O $HOME_BIN_PREFIX"/termux-url-opener"

# Downloading the SENDGRID_API_KEY
# TODO: more private handling of this becuase Sendgrid will detect it if in public repository
# wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/SENDGRID_API_KEY -O $HOME_BIN_PREFIX"/SENDGRID_API_KEY"

# Downloading the standalone update script
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/f/update-config -O $HOME_BIN_PREFIX"/update-config"

# Set executable flag to all the scripts in ~/bin
chmod +x $HOME_BIN_PREFIX"/*"

# Generating the public key of the current device
pkg install openssh coreutils curl -y # curl will be used to send the public key via mail

# In case the key does not exist, generate it
if [ ! -f $HOME_PREFIX"/.ssh/id_rsa" ]; then
	ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
fi

# MY_SENDGRID_KEY=$(cat $HOME_BIN_PREFIX"/SENDGRID_API_KEY")

# DEST_EMAIL="doss@ai.cs.kobe-u.ac.jp"
# PUBKEY="$(cat ~/.ssh/id_rsa.pub)"

# curl --request POST \
#   --url https://api.sendgrid.com/v3/mail/send \
#   --header "Authorization: Bearer ${MY_SENDGRID_KEY}" \
#   --header 'Content-Type: application/json' \
# 	--data "$(echo '{"personalizations": [{"to": [{"email": "'${DEST_EMAIL}'"}]}],"from": {"email": "doss@genitconfig.me"},"subject": "Generate SSH Public Key","content": [{"type": "text/plain", "value": "'${PUBKEY}'"}]}')"

# echo ""
# echo ""
# echo "### ----------------------------------------------------------------------###"
# echo ""
# echo ""

echo $PUBKEY

# Reloads the current session with the new .bashrc
source ~/.bashrc
