#!/bin/bash

REVERSE_SHELL_PORT=$(cat ./f/DEFAULT_PORT)
REMOTE_HOSTNAME=$(cat ./f/REMOTE_HOSTNAME)

pkill -f "ssh -L ${REVERSE_SHELL_PORT}:127.0.0.1:${REVERSE_SHELL_PORT} ${REMOTE_HOSTNAME} -fNT"

ssh -L ${REVERSE_SHELL_PORT}:127.0.0.1:${REVERSE_SHELL_PORT} ${REMOTE_HOSTNAME} -fNT
