#!/bin/bash
# Maybe want a sweep kill of sshd first ?
killall sshd
sshd -p 8022
# TODO: Find a way to kill reverse connection if they already exist.
## Lazy method
pkill -f "ssh -R 25324:127.0.0.1:8022 foster -fNT"
pkill -f "ssh -R 25850:127.0.0.1:5901 foster -fNT"

ssh -R 25324:127.0.0.1:8022 foster -fNT # SSH Reverse shell
ssh -R 25850:127.0.0.1:5901 foster -fNT # VNC Tunnel via reverse shell
