#!/bin/bash
killall sshd
sshd -p 8022

REVERSE_SHELL_PORT=$(cat ~/bin/DEFAULT_PORT)
echo "# DEBUG: rev shell port: ${REVERSE_SHELL_PORT}"

REMOTE_HOSTNAME=$(cat ~/bin/REMOTE_HOSTNAME)
echo "# DEBUG: rev hostname: ${REMOTE_HOSTNAME}"

pkill -f "ssh -R ${REVERSE_SHELL_PORT}:127.0.0.1:8022 root@${REMOTE_HOSTNAME} -fNT"

ssh -R ${REVERSE_SHELL_PORT}:127.0.0.1:8022 root@${REMOTE_HOSTNAME} -fNT # SSH Reverse shell
