#!/bin/bash
# Maybe want a sweep kill of sshd first ?
killall sshd
sshd -p 8022

pkill -f "ssh -R 25850:localhost:5901 f-victory -fNT"
pkill -f "ssh -R 25324:localhost:8022 f-victory -fNT"

ssh -R 25324:localhost:8022 f-victory
ssh -R 25850:localhost:5901 f-victory
