#!/data/data/com.termux/files/usr/bin/bash
CHOICES=("0: Annuler" "1: Youtube Video 480p" "2: Youtube Audio MP3")

for (( IDX=0; IDX<"${#CHOICES[@]}" ; IDX++ )); do
	echo "${CHOICES[$IDX]}"
done
#Getting user choice
USERCHOICE=

while [[ -z "${USERCHOICE}" ]] || ! [[ "${USERCHOICE}" =~ ^[0-9]+$ ]] || [[ "${USERCHOICE}" < 0 ]] || [[ "${USERCHOICE}" > "${#CHOICES[@]}" ]]; do
	read -p "Votre choix ?" USERCHOICE
	if ! [[ "${USERCHOICE}" =~ ^[0-9]+$ ]] || [[ "${USERCHOICE}" < 0 ]] || [[ "${USERCHOICE}" > "${USERCHOICE}" ]]; then
		echo "Choix invalid. Veuillez reessayer."
	elif [[ "${USERCHOICE}" -eq 0 ]]; then
		echo "Au revoir"
	elif [[ "${USERCHOICE}" -eq 1 ]]; then
		echo "Youtube Video 480p"
		if [[ -z $1 ]]; then
			echo "Impossible de trouver l' URL demandee."
		else
			yt-dlp -f 18 $1
		fi
	elif [[ "${USERCHOICE}" -eq 2 ]]; then
		echo "Youtube Audio MP3"
		if [[ -z $1 ]]; then
			echo "Impossible de trouver l' URL demandee."
		else
			yt-dlp -f 249 $1
		fi
	# elif [[ "${USERCHOICE}" -eq 3 ]]; then
    #   echo "Selected Youtube 720p mode"
    #   if [[ -z $1 ]]; then
    #     echo "Could not find the Youtube URL"
    #   else
    #     yt-dlp -f 22 $1
    #   fi
	# elif [[ "${USERCHOICE}" -eq 4 ]]; then
   	#   echo "Selected Youtube 1080p mode"
    #   if [[ -z $1 ]]; then
    #     echo "Could not find the Youtube URL"
    #   else
    #    yt-dlp -f 303+251 $1
	#   fi
	fi
done
#echo "User entered ${USERCHOICE}"