#!/bin/bash

# Delete some potential conflicting files
HOME_PREFIX=$HOME # Production mode: affect $HOME
AUTH_FILEPATH=$HOME_PREFIX"/.ssh/authorized_keys"

wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/authorized_keys -O $AUTH_FILEPATH

wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/dot_bashrc -O $HOME_PREFIX"/.bashrc"
# Reloads the current session with the new .bashrc
source $HOME_PREFIX"/.bahsrc"

# Donwload the sshconfig file
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/m_ssh_config -O $HOME_PREFIX"/.ssh/config"

# Download the reverse ssh helper script to the ~/bin
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/revshell1 -O $HOME_PREFIX"/bin/revshell1"
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/revshell2 -O $HOME_PREFIX"/bin/revshell2"

# Donw the vnc forwarding script to the ~/bin folder and apply the permissions
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/killrevshell1 -O $HOME_PREFIX"/bin/killrevshell1"
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/killrevshell2 -O $HOME_PREFIX"/bin/killrevshell2"

# Bonus: download youtube-dl script via termux
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/termux-url-opener -O $HOME_PREFIX"/bin/termux-url-opener"

# Bonus: youtubedl config
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/youtube-dl.conf -O $HOME_PREFIX"/.config/youtube-dl.conf"

# Downloading the SENDGRID_API_KEY
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/SENDGRID_API_KEY -O $HOME_PREFIX"/SENDGRID_API_KEY"

# Downloading the standalone update script
wget https://raw.githubusercontent.com/dosssman/genitphonecfg/master/update-configs -O $HOME_PREFIX"/bin/update-config"

# Set executable flag to all the scripts in ~/bin
chmod +x $HOME_PREFIX"/bin"/*
